---
# vars file for join-workers
rule_list:
  - { proto: tcp, from_port: 6443, to_port: 6443, cidr_ip: 0.0.0.0/0 }
  - { proto: tcp, from_port: 22, to_port: 22, cidr_ip: 0.0.0.0/0 }
ec2_group_region: sa-east-1
ec2_group_vpc: 'vpc-e8c8cd93'
ec2_group_name: giropops
